import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {emailAccountsRoute} from '../account-sync/email-accounts.mjs';
import {accountSession} from '../account-sync/accounts.mjs';
const sql=new DatabaseSync(':memory:');
for(const f of ['accounts-schema.sql','email-schema.sql'])sql.exec(readFileSync(new URL('../account-sync/'+f,import.meta.url),'utf8'));
const prepare=q=>{const stmt=sql.prepare(q);const bound=(values=[])=>({bind:(...v)=>bound(v),first:async()=>stmt.get(...values),run:async()=>({meta:{changes:Number(stmt.run(...values).changes)}})});return bound();};
const DB={prepare,batch:async list=>{sql.exec('BEGIN');try{const out=[];for(const s of list)out.push(await s.run());sql.exec('COMMIT');return out;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const env={DB,FREE_ACCOUNT_SYNC:'true',EMAIL_ACCOUNT_SYNC:'true',ACCOUNT_PASSWORD_PEPPER:'p'.repeat(64),RESEND_API_KEY:'mock-only',ACCOUNT_EMAIL_FROM:'Aluni <test@example.org>',ACCOUNT_PUBLIC_URL:'https://preview.pages.dev/email-verify.html'};
let mails=[],fail=false;globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');if(fail)return{ok:false};mails.push(JSON.parse(options.body));return{ok:true};};
let ip=0;const call=async(action,body,override={})=>{const response=await emailAccountsRoute(new Request('https://worker/account/email/'+action,{method:'POST',headers:{'CF-Connecting-IP':'ip'+ip++},body:JSON.stringify(body)}),{...env,...override});return{status:response.status,...await response.json()};};
const email='alice@example.org',password='A-long-password-123';
let r=await call('register',{email,password,display_name:'Alice'});assert.equal(r.status,200);assert(!r.token);assert.match(r.message,/mở email/);assert.equal(mails.length,1);assert.equal(sql.prepare('SELECT COUNT(*) n FROM sync_account_sessions').get().n,0);
assert(!sql.prepare('SELECT login_hash FROM sync_accounts').get().login_hash.includes(password));
assert.equal((await call('login',{email,password})).code,'EMAIL_UNVERIFIED');
const tokenFrom=mail=>new URL(mail.text.match(/https:\/\/\S+/)[0]).hash.split('token=')[1];
const first=tokenFrom(mails[0]);assert(!JSON.stringify(sql.prepare('SELECT * FROM sync_email_tokens').all()).includes(first));
assert.equal((await call('verify',{token:first,password:'Wrong-password-123'})).status,400);
assert.equal((await call('verify',{token:first,password})).status,200);
assert.equal((await call('verify',{token:first,password})).status,400);
const login=await call('login',{email,password});assert.equal(login.status,200);const req=new Request('https://worker/student/saved-library',{headers:{Authorization:'Bearer '+login.token}});assert(await accountSession(req,env));
assert.equal((await call('forgot',{email})).status,200);const reset=tokenFrom(mails.at(-1));
assert.equal((await call('reset',{token:reset,password:'New-password-456'})).status,200);assert.equal(await accountSession(req,env),null);assert.equal((await call('reset',{token:reset,password})).status,400);
assert.equal((await call('login',{email,password})).status,401);assert.equal((await call('login',{email,password:'New-password-456'})).status,200);
assert.equal((await call('register',{email:'missing@example.org',password,display_name:'Missing'},{RESEND_API_KEY:''})).status,503);assert.equal(sql.prepare('SELECT COUNT(*) n FROM sync_accounts WHERE username=?').get('missing@example.org').n,0);
fail=true;assert.equal((await call('register',{email:'fail@example.org',password,display_name:'Fail'})).status,503);fail=false;
assert.equal((await call('resend',{email:'fail@example.org'})).status,200);const expiryToken=tokenFrom(mails.at(-1));sql.prepare('UPDATE sync_email_tokens SET expires_at=0 WHERE account_id=(SELECT id FROM sync_accounts WHERE username=?)').run('fail@example.org');assert.equal((await call('verify',{token:expiryToken,password})).status,400);
assert.equal((await call('register',{email:'race@example.org',password,display_name:'Race'})).status,200);const race=tokenFrom(mails.at(-1));const results=await Promise.all([call('verify',{token:race,password}),call('verify',{token:race,password})]);assert.deepEqual(results.map(x=>x.status).sort(),[200,400]);
assert.equal((await call('login',{email,password},{EMAIL_ACCOUNT_SYNC:'false'})).status,503);
console.log('PASS email: unverified login blocked, no registration session, password proof, hashed expiring single-use tokens, race protection, reset revokes sessions, mail failures fail closed.');
