import {parseHTML} from 'linkedom';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=readFileSync(new URL('../admin.html',import.meta.url),'utf8');
const {document}=parseHTML(html);
assert.equal(document.querySelector('#random50Scope option')?.value,'lesson1','lesson 01 is the safe default');
assert.equal(document.querySelectorAll('#random50Scope option').length,2);
assert.match(document.querySelector('#random50ImportCard').textContent,/Game phản xạ \+ Viết chữ Hán/);
assert.match(document.querySelector('#random50ImportCard').textContent,/Luyện đọc 50\+ được giữ nguyên/);
const helper=html.match(/function isFiftyPlusCourse\(course\)\{[^\n]+\}/)?.[0];
assert(helper,'50+ course detector exists');
const ctx={};vm.createContext(ctx);vm.runInContext(`${helper};this.detect=isFiftyPlusCourse`,ctx);
assert.equal(ctx.detect({id:'50plus',title:'Khóa khác'}),true);
assert.equal(ctx.detect({id:'course-a',title:'Tiếng Trung 50+'}),true);
assert.equal(ctx.detect({id:'npcr',title:'New Practical Chinese Reader'}),false);
const importer=html.match(/async function runRandom50Import\(\)\{[\s\S]*?\n\}/)?.[0]||'';
assert.match(importer,/\/admin\/vocabulary\/save/);
assert.match(importer,/reading:false,games:true,writing:true/);
assert.match(importer,/Không lấy từ Luyện đọc sang/);
const saveUsage=html.match(/function vocabUsageForLesson\(lesson\)\{[^\n]+\}/)?.[0]||'';
assert.match(saveUsage,/reading:false,games:true,writing:true/,'per-lesson saves enforce the same 50+ separation');
console.log('PASS Random 50+ Admin: safe lesson-01 default, XLSX bulk path, and Game/Writing-only usage.');
const game=readFileSync(new URL('../aluni-game.html',import.meta.url),'utf8');
assert.match(game,/if\(j\.random_missing\)/);
assert.match(game,/Chưa có kho Random của bài/);
assert.match(game,/lessonDataMessage=String\(j\.message/);
console.log('PASS Random 50+ Game: missing Random is shown instead of silently using the local fallback.');
