const LEVELS={hsk20:{version:"HSK 2.0",words:["150 từ","300 từ","600 từ","1.200 từ","2.500 từ","5.000+ từ"]},hsk30:{version:"HSK 3.0",words:["500 từ","1.272 từ","2.245 từ","3.245 từ","4.316 từ","5.456 từ"]}};
const FALLBACK_LESSONS=["Làm quen với bài học","Từ và cấu trúc trọng tâm","Nhận diện chữ Hán","Luyện ngữ pháp","Ôn tập theo chủ đề","Bài tập củng cố","Thực hành viết chữ","Kiểm tra nhanh","Vận dụng trong câu","Ôn tập tổng hợp","Thử thách cuối cấp","Đánh giá hoàn thành"];
const app=document.querySelector("#app"),banner=document.querySelector("#banner"),nav=document.querySelector("#mainNav"),menu=document.querySelector("#menuBtn");let state={tab:"hsk20",level:null,lesson:null,module:null,examVersion:"HSK 2.0",examLevel:"HSK 3"};
let writingCourses=[],grammarSets=[],catalogReady=false,catalogLoading=false;
menu.onclick=()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",open)};
nav.querySelectorAll("[data-tab]").forEach(btn=>btn.onclick=()=>{state={...state,tab:btn.dataset.tab,level:null,lesson:null};nav.classList.remove("open");render()});
function titleBlock(kicker,title,extra=""){return `<div class="page-head"><div><p class="eyebrow">${kicker}</p><h2>${title}</h2></div>${extra}</div>`}
function api(path){return String(window.ALUNI_API_BASE||"").replace(/\/+$/,'')+path}
function esc(value){return String(value??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function groupId(){return `${state.tab}_${state.level}`}
function courseMatches(course){const text=[course.id,course.code,course.slug,course.title,course.name].filter(Boolean).join(" ").toLowerCase().replace(/\s+/g,"");const version=state.tab==="hsk20"?/(hsk2\.0|hsk20)/:/(hsk3\.0|hsk30)/;return version.test(text)&&new RegExp(`(?:cấp|cap|hsk|level)[-_ ]?${state.level}(?!\\d)`).test(text)}
function realLessons(){const course=writingCourses.find(courseMatches),writing=course?.lessons||[],grammar=grammarSets.filter(x=>x.free_group===groupId()),rows=new Map();writing.forEach((x,i)=>{const n=Number(x.number??x.lesson_number??i+1);rows.set(n,{number:n,title:x.title||x.name||`Bài ${n}`,writing:x})});grammar.forEach((x,i)=>{const n=Number(x.lesson_number||i+1),row=rows.get(n)||{number:n,title:x.lesson_title||x.course_title||`Bài ${n}`};row.grammar=x;rows.set(n,row)});return [...rows.values()].sort((a,b)=>a.number-b.number)}
async function loadCatalogs(){if(catalogReady||catalogLoading)return;catalogLoading=true;try{const [w,g]=await Promise.all([fetch(api('/content/catalog'),{cache:'default'}),fetch(api('/grammar/catalog'),{cache:'default'})]);const [wj,gj]=await Promise.all([w.ok?w.json():{},g.ok?g.json():{}]);writingCourses=Array.isArray(wj.courses)?wj.courses:[];grammarSets=Array.isArray(gj.sets)?gj.sets:[];catalogReady=true}catch(e){console.warn('Aluni HSK catalog:',e)}finally{catalogLoading=false;if(state.level&&!state.lesson)renderLessons()}}
function render(){nav.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===state.tab));banner.hidden=!!state.lesson;if(LEVELS[state.tab]&&!catalogReady)loadCatalogs();if(state.lesson)return renderLesson();if(state.level)return renderLessons();if(LEVELS[state.tab])return renderLevels();if(state.tab==="exam")return renderExam();if(state.tab==="hskk")return renderHskk();renderProgress()}
function renderLevels(){const data=LEVELS[state.tab];app.innerHTML=titleBlock("Không gian học tập",data.version)+`<p class="intro"><b>${data.version}</b> · Chọn cấp độ để mở toàn bộ danh sách bài từ trên xuống.</p><div class="levels">${data.words.map((w,i)=>`<button class="level" data-level="${i+1}"><span class="num">${i+1}</span><span><small>${data.version}</small><h3>HSK ${i+1}</h3><p>${w}</p><b>Xem tất cả bài →</b></span></button>`).join("")}</div>`;app.querySelectorAll("[data-level]").forEach(b=>b.onclick=()=>{state.level=+b.dataset.level;render();scrollTo(0,0)})}
function renderLessons(){const data=LEVELS[state.tab],live=realLessons(),rows=live.length?live:FALLBACK_LESSONS.map((title,i)=>({number:i+1,title})),status=catalogLoading?'Đang tải dữ liệu…':live.length?`${live.length} bài`:'Chưa có dữ liệu';app.innerHTML=`<button class="back" id="back">← Chọn cấp độ khác</button>${titleBlock("KHO BÀI HỌC",`${data.version} – Cấp ${state.level}`,`<span class="waiting">${status}</span>`)}<div class="lessons course-lesson-list">${rows.map(row=>`<article class="course-lesson-row"><div class="course-lesson-copy"><strong>🔒 Bài ${String(row.number).padStart(2,"0")} · ${esc(row.title)}</strong><small>Nhấn Học bài để mở Viết chữ và Ngữ pháp &amp; Bài tập</small></div><button class="course-study-btn" data-lesson="${row.number}">✍ Học bài</button></article>`).join("")}</div>`;document.querySelector("#back").onclick=()=>{state.level=null;render()};app.querySelectorAll("[data-lesson]").forEach(b=>b.onclick=()=>{state.lesson=+b.dataset.lesson;state.module=null;render();scrollTo(0,0)})}
function activeRow(){return realLessons().find(x=>x.number===state.lesson)||{number:state.lesson,title:FALLBACK_LESSONS[state.lesson-1]||`Bài ${state.lesson}`}}
function renderLesson(){const data=LEVELS[state.tab],row=activeRow(),wordCount=row.writing?.items?.length;app.innerHTML=`<button class="back" id="back">← Danh sách bài học</button><section class="learning-shell lesson-overview">${titleBlock(`${data.version} · HSK ${state.level}`,`Bài ${String(state.lesson).padStart(2,"0")}. ${esc(row.title)}`,`<span class="waiting">${row.writing||row.grammar?'Dữ liệu Aluni':'Đang cập nhật'}</span>`)}<p class="content-label">${String(state.lesson).padStart(2,"0")} · NỘI DUNG BÀI</p><div class="lesson-actions"><article class="lesson-action"><span>✍ Viết chữ${wordCount?` · ${wordCount} từ`:''}</span><button data-module="writing">Luyện viết</button></article><article class="lesson-action"><span>📚 Ngữ pháp &amp; Bài tập</span><button data-module="grammar">Học ngay</button></article></div><div id="module" class="module-detail" hidden></div></section>`;document.querySelector("#back").onclick=()=>{state.lesson=null;state.module=null;render()};app.querySelectorAll("[data-module]").forEach(b=>b.onclick=()=>{state.module=b.dataset.module;drawModule();document.querySelector("#module")?.scrollIntoView({behavior:"smooth",block:"start"})})}
async function fetchWriting(row){if(!row.writing)return null;if(Array.isArray(row.writing.items))return row.writing;const course=writingCourses.find(courseMatches),r=await fetch(api(`/content/lesson?course_id=${encodeURIComponent(course.id)}&lesson_number=${encodeURIComponent(row.number)}`),{cache:'default'});if(!r.ok)throw new Error('Chưa tải được bài Viết chữ.');const j=await r.json();row.writing=j.lesson||row.writing;return row.writing}
async function fetchGrammar(row){if(!row.grammar)return null;const r=await fetch(api(`/grammar/set?id=${encodeURIComponent(row.grammar.id)}&source=free`),{cache:'default'});if(!r.ok)throw new Error('Chưa tải được Ngữ pháp & Bài tập.');return r.json()}
function writingHtml(lesson){const items=lesson?.items||[];if(!items.length)return emptyModule('✍','Viết chữ đang được cập nhật','Bài này chưa có danh sách chữ.');return `<div class="word-grid">${items.map(x=>`<article class="word-card"><b>${esc(x.hanzi)}</b><span>${esc(x.pinyin||'')}</span><p>${esc(x.vi||'')}</p><a href="../index.html#writingSection">Mở khung luyện viết →</a></article>`).join('')}</div>`}
function grammarHtml(data){const set=data?.set||data,questions=data?.questions||[];if(!set?.title)return emptyModule('📚','Ngữ pháp đang được cập nhật','Bài này chưa có nội dung ngữ pháp.');return `<div class="grammar-grid"><div class="grammar-box"><span class="grammar-label">NGỮ PHÁP</span><h3>${esc(set.title)}</h3>${set.pinyin?`<div class="pinyin">${esc(set.pinyin)}</div>`:''}${set.explanation?`<p>${esc(set.explanation)}</p>`:''}${set.formula?`<div class="formula">${esc(set.formula)}</div>`:''}${(set.examples||[]).map(x=>`<div class="example"><b>${esc(x.hanzi)}</b><span>${esc(x.pinyin||'')}</span><small>${esc(x.vi||'')}</small></div>`).join('')}</div><div class="grammar-box"><span class="grammar-label">BÀI TẬP</span>${questions.length?questions.map((q,i)=>`<div class="question"><b>Câu ${i+1}. ${esc(q.prompt)}</b>${(q.options||[]).map((o,k)=>`<label><input type="radio" name="q${i}" value="${k}"> ${esc(o)}</label>`).join('')}</div>`).join('')+'<button class="primary" id="scoreBtn">Chấm điểm</button><div id="scoreResult"></div>':'<p>Bài tập đang được cập nhật.</p>'}</div></div>`}
function emptyModule(icon,title,text){return `<div class="module"><div class="module-card"><span class="module-icon">${icon}</span><h3>${title}</h3><p>${text}</p></div></div>`}
async function drawModule(){app.querySelectorAll("[data-module]").forEach(b=>b.classList.toggle("active",b.dataset.module===state.module));const target=document.querySelector("#module"),row=activeRow();target.hidden=false;target.innerHTML=emptyModule('…','Đang tải dữ liệu Aluni','Vui lòng chờ trong giây lát.');try{if(state.module==='writing')target.innerHTML=writingHtml(await fetchWriting(row));else{const data=await fetchGrammar(row);target.innerHTML=grammarHtml(data);const btn=document.querySelector('#scoreBtn');if(btn)btn.onclick=()=>scoreGrammar(data)}}catch(e){target.innerHTML=emptyModule('↻','Chưa mở được dữ liệu',esc(e.message))}}
function scoreGrammar(data){const questions=data?.questions||[];let correct=0,answered=0;questions.forEach((q,i)=>{const chosen=document.querySelector(`input[name="q${i}"]:checked`);if(chosen){answered++;if(Number(chosen.value)===Number(q.correct_index))correct++}});document.querySelector('#scoreResult').textContent=`Kết quả: ${correct}/${questions.length} câu đúng${answered<questions.length?' · Còn câu chưa trả lời':''}`;localStorage.setItem(`aluni_hsk_${state.tab}_${state.level}_${state.lesson}`,JSON.stringify({correct,total:questions.length,updated_at:Date.now()}))}
function renderExam(){app.innerHTML=titleBlock("Luyện đề HSK","Chọn đề phù hợp")+`<section class="panel"><div class="panel-side"><h3>Luyện đúng cấu trúc đề thi</h3><p>Nghe, đọc, viết và theo dõi thời gian làm bài.</p></div><div class="panel-main"><h3>Hệ HSK</h3><div class="choice-grid">${["HSK 2.0","HSK 3.0"].map(v=>`<button class="choice ${state.examVersion===v?"active":""}" data-version="${v}">${v}</button>`).join("")}</div><h3>Cấp độ</h3><div class="choice-grid">${[1,2,3,4,5,6].map(v=>`<button class="choice ${state.examLevel===`HSK ${v}`?"active":""}" data-exam="${v}">HSK ${v}</button>`).join("")}</div><button class="primary" style="margin-top:20px">Bắt đầu khi có dữ liệu đề</button></div></section>`;app.querySelectorAll("[data-version]").forEach(b=>b.onclick=()=>{state.examVersion=b.dataset.version;renderExam()});app.querySelectorAll("[data-exam]").forEach(b=>b.onclick=()=>{state.examLevel=`HSK ${b.dataset.exam}`;renderExam()})}
function renderHskk(){app.innerHTML=titleBlock("Luyện nói HSKK","Chọn trình độ")+`<div class="levels">${["Sơ cấp","Trung cấp","Cao cấp"].map((x,i)=>`<button class="level"><span class="num">🎙</span><span><small>HSKK</small><h3>${x}</h3><p>${["Nghe · Nhắc lại","Tranh · Trả lời","Đọc · Trình bày"][i]}</p><b>Vào phòng luyện →</b></span></button>`).join("")}</div>`}
function renderProgress(){app.innerHTML=titleBlock("Kết quả học tập","Hành trình của bạn")+`<section class="progress"><div class="card"><div class="metrics"><div class="metric"><b>0</b><small>Bài hoàn thành</small></div><div class="metric"><b>0</b><small>Điểm trung bình</small></div><div class="metric"><b>0</b><small>Ngày học</small></div></div><p class="intro" style="margin-top:18px">Không đăng nhập vẫn học bình thường. Tiến độ có tên và lịch sử lâu dài chỉ được lưu khi học viên tự nguyện kết nối tài khoản.</p></div><aside class="panel-side" style="border-radius:22px"><h3>Đăng nhập khi bạn muốn</h3><p>Lưu bài đã học, điểm luyện đề và tiếp tục trên thiết bị khác. Không che hoặc khóa nội dung miễn phí.</p><a class="primary" href="https://tieng-trung-aluni.nhangohcm.chatgpt.site/" target="_blank" rel="noopener" style="display:inline-block;text-decoration:none">Tìm hiểu khóa học</a></aside></section>`}
render();
