const LEVELS={hsk20:{version:"HSK 2.0",words:["150 từ","300 từ","600 từ","1.200 từ","2.500 từ","5.000+ từ"]},hsk30:{version:"HSK 3.0",words:["500 từ","1.272 từ","2.245 từ","3.245 từ","4.316 từ","5.456 từ"]}};
const LESSONS=["Làm quen với bài học","Từ và cấu trúc trọng tâm","Nhận diện chữ Hán","Luyện ngữ pháp","Ôn tập theo chủ đề","Bài tập củng cố","Thực hành viết chữ","Kiểm tra nhanh","Vận dụng trong câu","Ôn tập tổng hợp","Thử thách cuối cấp","Đánh giá hoàn thành"];
const app=document.querySelector("#app"),banner=document.querySelector("#banner"),nav=document.querySelector("#mainNav"),menu=document.querySelector("#menuBtn");let state={tab:"hsk20",level:null,lesson:null,module:"writing",examVersion:"HSK 2.0",examLevel:"HSK 3"};
menu.onclick=()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",open)};
nav.querySelectorAll("[data-tab]").forEach(btn=>btn.onclick=()=>{state={...state,tab:btn.dataset.tab,level:null,lesson:null};nav.classList.remove("open");render()});
function titleBlock(kicker,title,extra=""){return `<div class="page-head"><div><p class="eyebrow">${kicker}</p><h2>${title}</h2></div>${extra}</div>`}
function render(){nav.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===state.tab));banner.hidden=!!state.lesson;if(state.lesson)return renderLesson();if(state.level)return renderLessons();if(LEVELS[state.tab])return renderLevels();if(state.tab==="exam")return renderExam();if(state.tab==="hskk")return renderHskk();renderProgress()}
function renderLevels(){const data=LEVELS[state.tab];app.innerHTML=titleBlock("Không gian học tập",data.version)+`<p class="intro"><b>${data.version}</b> · Chọn cấp độ để mở toàn bộ danh sách bài từ trên xuống.</p><div class="levels">${data.words.map((w,i)=>`<button class="level" data-level="${i+1}"><span class="num">${i+1}</span><span><small>${data.version}</small><h3>HSK ${i+1}</h3><p>${w}</p><b>Xem tất cả bài →</b></span></button>`).join("")}</div>`;app.querySelectorAll("[data-level]").forEach(b=>b.onclick=()=>{state.level=+b.dataset.level;render();scrollTo(0,0)})}
function renderLessons(){const data=LEVELS[state.tab];app.innerHTML=`<button class="back" id="back">← Quay lại các cấp độ</button>${titleBlock(data.version,`HSK ${state.level} · Danh sách bài`,`<span class="waiting">Chờ dữ liệu chính thức</span>`)}<p class="intro">Tất cả bài được xếp liên tục từ trên xuống. Mỗi bài mở đúng 2 khu: <b>Viết chữ</b> và <b>Ngữ pháp &amp; Bài tập</b>.</p><div class="lessons">${LESSONS.map((n,i)=>`<button class="lesson" data-lesson="${i+1}"><span class="lesson-num">${String(i+1).padStart(2,"0")}</span><span><strong>${n}</strong><small>Viết chữ · Ngữ pháp &amp; Bài tập</small></span><i class="waiting">Chờ dữ liệu</i><b>›</b></button>`).join("")}</div>`;document.querySelector("#back").onclick=()=>{state.level=null;render()};app.querySelectorAll("[data-lesson]").forEach(b=>b.onclick=()=>{state.lesson=+b.dataset.lesson;state.module="writing";render();scrollTo(0,0)})}
function renderLesson(){const data=LEVELS[state.tab],name=LESSONS[state.lesson-1];app.innerHTML=`<button class="back" id="back">← Danh sách bài</button><section class="learning-shell">${titleBlock(`${data.version} · HSK ${state.level}`,`Bài ${String(state.lesson).padStart(2,"0")}. ${name}`,`<span class="waiting">Khung chờ dữ liệu thật</span>`)}<div class="learning-tabs"><button data-module="writing">✍ Viết chữ</button><button data-module="grammar">📚 Ngữ pháp &amp; Bài tập</button></div><div id="module"></div></section>`;document.querySelector("#back").onclick=()=>{state.lesson=null;render()};app.querySelectorAll("[data-module]").forEach(b=>b.onclick=()=>{state.module=b.dataset.module;drawModule()});drawModule()}
function drawModule(){app.querySelectorAll("[data-module]").forEach(b=>b.classList.toggle("active",b.dataset.module===state.module));const target=document.querySelector("#module");target.innerHTML=state.module==="writing"?`<div class="module"><div class="module-card"><span class="module-icon">✍</span><h3>Viết chữ theo bài</h3><p>Khung này sẽ dùng lại thao tác tra chữ, xem nét, nghe âm và luyện viết đang hoạt động mượt trên Aluni.</p><button class="primary">Chờ nối dữ liệu Viết chữ</button></div></div>`:`<div class="grammar-grid"><div class="grammar-box"><h4>Ngữ pháp trọng tâm</h4><div class="formula">Chủ ngữ + Thời gian + Động từ + Tân ngữ</div><p>Nội dung, ví dụ, pinyin và nghĩa Việt sẽ lấy trực tiếp từ kho Ngữ pháp Aluni.</p></div><div class="grammar-box"><h4>Bài tập ngay sau cấu trúc</h4><p>Chọn đáp án, điền từ, sắp xếp câu và xem điểm ngay trong bài.</p><button class="primary">Chờ nối dữ liệu Bài tập</button></div></div>`}
function renderExam(){app.innerHTML=titleBlock("Luyện đề HSK","Chọn đề phù hợp")+`<section class="panel"><div class="panel-side"><h3>Luyện đúng cấu trúc đề thi</h3><p>Nghe, đọc, viết và theo dõi thời gian làm bài.</p></div><div class="panel-main"><h3>Hệ HSK</h3><div class="choice-grid">${["HSK 2.0","HSK 3.0"].map(v=>`<button class="choice ${state.examVersion===v?"active":""}" data-version="${v}">${v}</button>`).join("")}</div><h3>Cấp độ</h3><div class="choice-grid">${[1,2,3,4,5,6].map(v=>`<button class="choice ${state.examLevel===`HSK ${v}`?"active":""}" data-exam="${v}">HSK ${v}</button>`).join("")}</div><button class="primary" style="margin-top:20px">Bắt đầu khi có dữ liệu đề</button></div></section>`;app.querySelectorAll("[data-version]").forEach(b=>b.onclick=()=>{state.examVersion=b.dataset.version;renderExam()});app.querySelectorAll("[data-exam]").forEach(b=>b.onclick=()=>{state.examLevel=`HSK ${b.dataset.exam}`;renderExam()})}
function renderHskk(){app.innerHTML=titleBlock("Luyện nói HSKK","Chọn trình độ")+`<div class="levels">${["Sơ cấp","Trung cấp","Cao cấp"].map((x,i)=>`<button class="level"><span class="num">🎙</span><span><small>HSKK</small><h3>${x}</h3><p>${["Nghe · Nhắc lại","Tranh · Trả lời","Đọc · Trình bày"][i]}</p><b>Vào phòng luyện →</b></span></button>`).join("")}</div>`}
function renderProgress(){app.innerHTML=titleBlock("Kết quả học tập","Hành trình của bạn")+`<section class="progress"><div class="card"><div class="metrics"><div class="metric"><b>0</b><small>Bài hoàn thành</small></div><div class="metric"><b>0</b><small>Điểm trung bình</small></div><div class="metric"><b>0</b><small>Ngày học</small></div></div><p class="intro" style="margin-top:18px">Không đăng nhập vẫn học bình thường. Tiến độ có tên và lịch sử lâu dài chỉ được lưu khi học viên tự nguyện kết nối tài khoản.</p></div><aside class="panel-side" style="border-radius:22px"><h3>Đăng nhập khi bạn muốn</h3><p>Lưu bài đã học, điểm luyện đề và tiếp tục trên thiết bị khác. Không che hoặc khóa nội dung miễn phí.</p><a class="primary" href="https://tieng-trung-aluni.nhangohcm.chatgpt.site/" target="_blank" rel="noopener" style="display:inline-block;text-decoration:none">Tìm hiểu khóa học</a></aside></section>`}
render();
