const LEVELS={hsk20:{version:"HSK 2.0",words:["150 từ","300 từ","600 từ","1.200 từ","2.500 từ","5.000+ từ"]},hsk30:{version:"HSK 3.0",words:["500 từ","1.272 từ","2.245 từ","3.245 từ","4.316 từ","5.456 từ"]}};
const FALLBACK_LESSONS=["Làm quen với bài học","Từ và cấu trúc trọng tâm","Nhận diện chữ Hán","Luyện ngữ pháp","Ôn tập theo chủ đề","Bài tập củng cố","Thực hành viết chữ","Kiểm tra nhanh","Vận dụng trong câu","Ôn tập tổng hợp","Thử thách cuối cấp","Đánh giá hoàn thành"];
const app=document.querySelector("#app"),banner=document.querySelector("#banner"),nav=document.querySelector("#mainNav"),menu=document.querySelector("#menuBtn");let state={tab:"hsk20",level:null,lesson:null,module:null,examVersion:"hsk20",examLevel:1,examId:null,hskkLevel:null,hskkId:null};
let writingCourses=[],grammarSets=[],catalogReady=false,catalogLoading=false;
menu.onclick=()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",open)};
document.querySelector('#homeLink').onclick=e=>{e.preventDefault();navigate({tab:'hsk20',level:null,lesson:null,module:null,examId:null,hskkId:null});nav.classList.remove('open');scrollTo(0,0)};
function historyState(){return{...state}}
function navigate(patch){state={...state,...patch};history.pushState(historyState(),"",routeHash());render()}
function routeHash(){return `#${state.tab}${state.level?`/level-${state.level}`:''}${state.lesson?`/lesson-${state.lesson}`:''}${state.module?`/${state.module}`:''}${state.examId?`/exam-${state.examId}`:''}${state.hskkId?`/hskk-${state.hskkId}`:''}`}
history.replaceState(historyState(),"",routeHash());
window.addEventListener("popstate",event=>{state=event.state?{...state,...event.state}:{...state,tab:"hsk20",level:null,lesson:null,module:null};render();scrollTo(0,0)});
nav.querySelectorAll("[data-tab]").forEach(btn=>btn.onclick=()=>{navigate({tab:btn.dataset.tab,level:null,lesson:null,module:null,examId:null,hskkId:null});nav.classList.remove("open")});
function titleBlock(kicker,title,extra=""){return `<div class="page-head"><div><p class="eyebrow">${kicker}</p><h2>${title}</h2></div>${extra}</div>`}
function api(path){return String(window.ALUNI_API_BASE||"").replace(/\/+$/,'')+path}
function esc(value){return String(value??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function groupId(){return `${state.tab}_${state.level}`}
function courseMatches(course){const text=[course.id,course.code,course.slug,course.title,course.name].filter(Boolean).join(" ").toLowerCase().replace(/\s+/g,"");const version=state.tab==="hsk20"?/(hsk2\.0|hsk20)/:/(hsk3\.0|hsk30)/;return version.test(text)&&new RegExp(`(?:cấp|cap|hsk|level)[-_ ]?${state.level}(?!\\d)`).test(text)}
function realLessons(){const course=writingCourses.find(courseMatches),writing=course?.lessons||[],grammar=grammarSets.filter(x=>x.free_group===groupId()),rows=new Map();writing.forEach((x,i)=>{const n=Number(x.number??x.lesson_number??i+1);rows.set(n,{number:n,title:x.title||x.name||`Bài ${n}`,writing:x})});grammar.forEach((x,i)=>{const n=Number(x.lesson_number||i+1),row=rows.get(n)||{number:n,title:x.lesson_title||x.course_title||`Bài ${n}`};row.grammar=x;rows.set(n,row)});return [...rows.values()].sort((a,b)=>a.number-b.number)}
async function loadCatalogs(){if(catalogReady||catalogLoading)return;catalogLoading=true;try{const [w,g]=await Promise.all([fetch(api('/content/catalog'),{cache:'default'}),fetch(api('/grammar/catalog'),{cache:'default'})]);const [wj,gj]=await Promise.all([w.ok?w.json():{},g.ok?g.json():{}]);writingCourses=Array.isArray(wj.courses)?wj.courses:[];grammarSets=Array.isArray(gj.sets)?gj.sets:[];catalogReady=true}catch(e){console.warn('Aluni HSK catalog:',e)}finally{catalogLoading=false;if(state.level&&!state.lesson)renderLessons()}}
function render(){nav.querySelectorAll("[data-tab]").forEach(b=>b.classList.toggle("active",b.dataset.tab===state.tab));banner.hidden=!!(state.lesson||state.examId||state.hskkId);if(LEVELS[state.tab]&&!catalogReady)loadCatalogs();if(state.lesson)return renderLesson();if(state.level)return renderLessons();if(LEVELS[state.tab])return renderLevels();if(state.tab==="exam")return state.examId?renderExamScreen():renderExam();if(state.tab==="hskk")return state.hskkId?renderHskkScreen():renderHskk();renderProgress()}
function renderLevels(){const data=LEVELS[state.tab];app.innerHTML=titleBlock("Không gian học tập",data.version)+`<p class="intro"><b>${data.version}</b> · Chọn cấp độ để mở toàn bộ danh sách bài từ trên xuống.</p><div class="levels">${data.words.map((w,i)=>`<button class="level" data-level="${i+1}"><span class="num">${i+1}</span><span><small>${data.version}</small><h3>HSK ${i+1}</h3><p>${w}</p><b>Xem tất cả bài →</b></span></button>`).join("")}</div>`;app.querySelectorAll("[data-level]").forEach(b=>b.onclick=()=>{navigate({level:+b.dataset.level,lesson:null,module:null});scrollTo(0,0)})}
function renderLessons(){const data=LEVELS[state.tab],live=realLessons(),rows=live.length?live:FALLBACK_LESSONS.map((title,i)=>({number:i+1,title})),status=catalogLoading?'Đang tải dữ liệu…':live.length?`${live.length} bài`:'Chưa có dữ liệu';app.innerHTML=`<button class="back" id="back">← Chọn cấp độ khác</button>${titleBlock("KHO BÀI HỌC",`${data.version} – Cấp ${state.level}`,`<span class="waiting">${status}</span>`)}<div class="lessons course-lesson-list">${rows.map(row=>`<article class="course-lesson-row" role="button" tabindex="0" data-lesson="${row.number}" aria-label="Mở bài ${row.number}: ${esc(row.title)}"><div class="course-lesson-copy"><strong>🔒 Bài ${String(row.number).padStart(2,"0")} · ${esc(row.title)}</strong><small>Nhấn vào bài để mở Viết chữ và Ngữ pháp &amp; Bài tập</small></div><span class="course-study-btn">✍ Học bài</span></article>`).join("")}</div>`;document.querySelector("#back").onclick=()=>history.back();const open=b=>{navigate({lesson:+b.dataset.lesson,module:null});scrollTo(0,0)};app.querySelectorAll("[data-lesson]").forEach(b=>{b.onclick=()=>open(b);b.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open(b)}}})}
function activeRow(){return realLessons().find(x=>x.number===state.lesson)||{number:state.lesson,title:FALLBACK_LESSONS[state.lesson-1]||`Bài ${state.lesson}`}}
function renderLesson(){if(state.module)return renderStudyScreen();const data=LEVELS[state.tab],row=activeRow(),wordCount=row.writing?.items?.length;app.innerHTML=`<button class="back" id="back">← Danh sách bài học</button><section class="learning-shell lesson-overview">${titleBlock(`${data.version} · HSK ${state.level}`,`Bài ${String(state.lesson).padStart(2,"0")}. ${esc(row.title)}`,`<span class="waiting">${row.writing||row.grammar?'Dữ liệu Aluni':'Đang cập nhật'}</span>`)}<p class="content-label">${String(state.lesson).padStart(2,"0")} · NỘI DUNG BÀI</p><div class="lesson-actions"><article class="lesson-action lesson-action-click" role="button" tabindex="0" data-module="writing"><span>✍ Viết chữ${wordCount?` · ${wordCount} từ`:''}</span><b>Luyện viết</b></article><article class="lesson-action lesson-action-click" role="button" tabindex="0" data-module="grammar"><span>📚 Ngữ pháp &amp; Bài tập</span><b>Học ngay</b></article></div></section>`;document.querySelector("#back").onclick=()=>history.back();const open=b=>navigate({module:b.dataset.module});app.querySelectorAll("[data-module]").forEach(b=>{b.onclick=()=>open(b);b.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open(b)}}})}
function renderStudyScreen(){const data=LEVELS[state.tab],row=activeRow(),label=state.module==="writing"?"Viết chữ":"Ngữ pháp & Bài tập";app.innerHTML=`<button class="back" id="back">← Nội dung bài</button><section class="learning-shell study-screen">${titleBlock(`${data.version} · HSK ${state.level} · Bài ${String(state.lesson).padStart(2,"0")}`,label,`<span class="waiting">${row.writing||row.grammar?'Dữ liệu Aluni':'Đang cập nhật'}</span>`)}<div id="module" class="module-detail"></div></section>`;document.querySelector("#back").onclick=()=>history.back();drawModule()}
async function fetchWriting(row){if(!row.writing)return null;if(Array.isArray(row.writing.items))return row.writing;const course=writingCourses.find(courseMatches),r=await fetch(api(`/content/lesson?course_id=${encodeURIComponent(course.id)}&lesson_number=${encodeURIComponent(row.number)}`),{cache:'default'});if(!r.ok)throw new Error('Chưa tải được bài Viết chữ.');const j=await r.json();row.writing=j.lesson||row.writing;return row.writing}
async function fetchGrammar(row){if(!row.grammar)return null;const r=await fetch(api(`/grammar/set?id=${encodeURIComponent(row.grammar.id)}&source=free`),{cache:'default'});if(!r.ok)throw new Error('Chưa tải được Ngữ pháp & Bài tập.');return r.json()}
function writingHtml(lesson){const items=lesson?.items||[];if(!items.length)return emptyModule('✍','Viết chữ đang được cập nhật','Bài này chưa có danh sách chữ.');return `<div class="word-grid">${items.map(x=>`<article class="word-card"><b>${esc(x.hanzi)}</b><span>${esc(x.pinyin||'')}</span><p>${esc(x.vi||'')}</p><a href="../index.html#writingSection">Mở khung luyện viết →</a></article>`).join('')}</div>`}
function grammarHtml(data){const set=data?.set||data,questions=data?.questions||[];if(!set?.title)return emptyModule('📚','Ngữ pháp đang được cập nhật','Bài này chưa có nội dung ngữ pháp.');return `<div class="grammar-grid"><div class="grammar-box"><span class="grammar-label">NGỮ PHÁP</span><h3>${esc(set.title)}</h3>${set.pinyin?`<div class="pinyin">${esc(set.pinyin)}</div>`:''}${set.explanation?`<p>${esc(set.explanation)}</p>`:''}${set.formula?`<div class="formula">${esc(set.formula)}</div>`:''}${(set.examples||[]).map(x=>`<div class="example"><b>${esc(x.hanzi)}</b><span>${esc(x.pinyin||'')}</span><small>${esc(x.vi||'')}</small></div>`).join('')}</div><div class="grammar-box"><span class="grammar-label">BÀI TẬP</span>${questions.length?questions.map((q,i)=>`<div class="question"><b>Câu ${i+1}. ${esc(q.prompt)}</b>${(q.options||[]).map((o,k)=>`<label><input type="radio" name="q${i}" value="${k}"> ${esc(o)}</label>`).join('')}</div>`).join('')+'<button class="primary" id="scoreBtn">Chấm điểm</button><div id="scoreResult"></div>':'<p>Bài tập đang được cập nhật.</p>'}</div></div>`}
function emptyModule(icon,title,text){return `<div class="module"><div class="module-card"><span class="module-icon">${icon}</span><h3>${title}</h3><p>${text}</p></div></div>`}
async function drawModule(){app.querySelectorAll("[data-module]").forEach(b=>b.classList.toggle("active",b.dataset.module===state.module));const target=document.querySelector("#module"),row=activeRow();target.hidden=false;target.innerHTML=emptyModule('…','Đang tải dữ liệu Aluni','Vui lòng chờ trong giây lát.');try{if(state.module==='writing')target.innerHTML=writingHtml(await fetchWriting(row));else{const data=await fetchGrammar(row);target.innerHTML=grammarHtml(data);const btn=document.querySelector('#scoreBtn');if(btn)btn.onclick=()=>scoreGrammar(data)}}catch(e){target.innerHTML=emptyModule('↻','Chưa mở được dữ liệu',esc(e.message))}}
function scoreGrammar(data){const questions=data?.questions||[],row=activeRow();let correct=0,answered=0;questions.forEach((q,i)=>{const chosen=document.querySelector(`input[name="q${i}"]:checked`);if(chosen){answered++;if(Number(chosen.value)===Number(q.correct_index))correct++}});document.querySelector('#scoreResult').textContent=`Kết quả: ${correct}/${questions.length} câu đúng${answered<questions.length?' · Còn câu chưa trả lời':''}`;localStorage.setItem(`aluni_hsk_${state.tab}_${state.level}_${state.lesson}`,JSON.stringify({type:'grammar',title:`${LEVELS[state.tab].version} · Bài ${state.lesson}: ${row.title}`,correct,total:questions.length,updated_at:Date.now()}))}
async function getJson(path){const r=await fetch(api(path),{cache:'no-store'});if(!r.ok)throw new Error('Chưa tải được dữ liệu.');return r.json()}
async function renderExam(){app.innerHTML=titleBlock("Luyện đề HSK","Chọn đề phù hợp")+`<section class="panel"><div class="panel-side"><h3>Luyện đúng cấu trúc đề thi</h3><p>Nghe, đọc, viết và theo dõi thời gian làm bài.</p></div><div class="panel-main"><h3>Hệ HSK</h3><div class="choice-grid">${[["hsk20","HSK 2.0"],["hsk30","HSK 3.0"]].map(([v,t])=>`<button class="choice ${state.examVersion===v?"active":""}" data-version="${v}">${t}</button>`).join("")}</div><h3>Cấp độ</h3><div class="choice-grid">${[1,2,3,4,5,6].map(v=>`<button class="choice ${Number(state.examLevel)===v?"active":""}" data-exam="${v}">HSK ${v}</button>`).join("")}</div><div id="examSets" class="loading-box">Đang tải danh sách đề…</div></div></section>`;app.querySelectorAll("[data-version]").forEach(b=>b.onclick=()=>{state.examVersion=b.dataset.version;renderExam()});app.querySelectorAll("[data-exam]").forEach(b=>b.onclick=()=>{state.examLevel=+b.dataset.exam;renderExam()});try{const j=await getJson('/hsk/exams'),list=(j.sets||[]).filter(x=>x.version===state.examVersion&&Number(x.level)===state.examLevel),box=document.querySelector('#examSets');box.innerHTML=list.length?`<div class="set-list">${list.map(x=>`<button class="set-card" data-id="${esc(x.id)}"><span><small>${esc(x.code)}</small><b>${esc(x.title)}</b><em>${Number(x.duration_minutes)||0} phút</em></span><strong>Làm đề →</strong></button>`).join('')}</div>`:'<div class="empty-list">Chưa có đề đã xuất bản cho cấp độ này.</div>';box.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>navigate({examId:b.dataset.id}))}catch(e){document.querySelector('#examSets').innerHTML=`<div class="empty-list">${esc(e.message)}</div>`}}
async function renderExamScreen(){
  app.innerHTML=`<button class="back" id="back">← Danh sách đề</button><section class="learning-shell"><div id="examDetail" class="loading-box">Đang mở đề…</div></section>`;
  document.querySelector('#back').onclick=()=>history.back();
  try{
    const j=await getJson('/hsk/exam?id='+encodeURIComponent(state.examId)),set=j.set||{},questions=j.questions||[],box=document.querySelector('#examDetail');
    const questionHtml=questions.map((q,i)=>{
      let opts=Array.isArray(q.options)?q.options:[];
      if(!opts.length){try{opts=JSON.parse(q.options_json||'[]')}catch{opts=[]}}
      const answerInput=opts.length?opts.map((o,k)=>`<label><input type="radio" name="eq${i}" value="${String.fromCharCode(65+k)}"> ${esc(o)}</label>`).join(''):'<textarea rows="4" placeholder="Nhập câu trả lời"></textarea>';
      return `<article class="exam-question" data-question-id="${esc(q.id)}"><h3>Câu ${i+1}. ${esc(q.prompt)}</h3>${q.passage?`<p>${esc(q.passage)}</p>`:''}${q.audio_url?`<audio controls preload="none" src="${esc(q.audio_url)}"></audio>`:''}${q.image_url?`<img src="${esc(q.image_url)}" alt="Hình câu ${i+1}">`:''}${answerInput}<div class="answer-feedback" id="feedback${i}"></div></article>`;
    }).join('');
    box.innerHTML=titleBlock(`${set.version==='hsk30'?'HSK 3.0':'HSK 2.0'} · Cấp ${set.level}`,esc(set.title),`<span class="waiting">${Number(set.duration_minutes)||0} phút</span>`)+`<p class="intro">${esc(set.instructions||'Hoàn thành lần lượt các câu hỏi.')}</p><div class="exam-questions">${questionHtml}</div><button class="primary" id="finishExam">Nộp bài và chấm điểm</button><div class="status-line" id="examResult"></div>`;
    document.querySelector('#finishExam').onclick=async()=>{
      const btn=document.querySelector('#finishExam'),result=document.querySelector('#examResult');
      const answers=questions.map((q,i)=>{const card=document.querySelectorAll('.exam-question')[i];return{question_id:q.id,answer:card.querySelector('input:checked')?.value||card.querySelector('textarea')?.value.trim()||''}});
      btn.disabled=true;result.textContent='Đang chấm bài…';
      try{
        const r=await fetch(api('/hsk/exam/submit'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({exam_id:state.examId,answers})}),data=await r.json();
        if(!r.ok)throw new Error(data.error||'Chưa chấm được bài.');
        result.textContent=`Kết quả: ${data.score}/${data.auto_graded_points} điểm tự động${data.pending_manual_points?` · ${data.pending_manual_points} điểm cần chấm thủ công`:''}`;
        btn.textContent='Đã nộp bài và chấm điểm';
        data.results.forEach((x,i)=>{const el=document.querySelector('#feedback'+i);el.className='answer-feedback '+(x.correct===true?'correct':x.correct===false?'wrong':'pending');if(x.correct===true)el.textContent='✓ Đúng';else if(x.correct===false)el.innerHTML=`✕ Chưa đúng · Đáp án: <b>${esc(x.correct_answer)}</b>${x.explanation?`<br>${esc(x.explanation)}`:''}`;else el.textContent='Đã ghi nhận · Câu này cần chấm thủ công'});
        localStorage.setItem('aluni_hsk_exam_'+state.examId,JSON.stringify({type:'exam',title:set.title||'Đề luyện HSK',version:set.version,level:set.level,score:data.score,total:data.total_points,updated_at:Date.now()}));
      }catch(e){result.textContent=e.message;btn.disabled=false}
    };
  }catch(e){document.querySelector('#examDetail').innerHTML=emptyModule('↻','Chưa mở được đề',esc(e.message))}
}
const HSKK_LEVELS=[["primary","Sơ cấp","Nghe · Nhắc lại"],["intermediate","Trung cấp","Tranh · Trả lời"],["advanced","Cao cấp","Đọc · Trình bày"]];
async function renderHskk(){app.innerHTML=titleBlock("Luyện nói HSKK","Chọn trình độ")+`<div class="levels">${HSKK_LEVELS.map(([v,x,d])=>`<button class="level" data-level="${v}"><span class="num">🎙</span><span><small>HSKK</small><h3>${x}</h3><p>${d}</p><b>Xem bài luyện →</b></span></button>`).join("")}</div><div id="hskkSets"></div>`;app.querySelectorAll('[data-level]').forEach(b=>b.onclick=async()=>{state.hskkLevel=b.dataset.level;const box=document.querySelector('#hskkSets');box.innerHTML='<div class="loading-box">Đang tải bài luyện…</div>';try{const j=await getJson('/hsk/hskk'),list=(j.sets||[]).filter(x=>x.level===state.hskkLevel);box.innerHTML=list.length?`<div class="set-list">${list.map(x=>`<button class="set-card" data-id="${esc(x.id)}"><span><small>${esc(x.code)}</small><b>${esc(x.title)}</b><em>${Number(x.duration_minutes)||0} phút</em></span><strong>Vào luyện →</strong></button>`).join('')}</div>`:'<div class="empty-list">Chưa có bài đã xuất bản ở trình độ này.</div>';box.querySelectorAll('[data-id]').forEach(x=>x.onclick=()=>navigate({hskkId:x.dataset.id}))}catch(e){box.innerHTML=`<div class="empty-list">${esc(e.message)}</div>`}})}
async function renderHskkScreen(){app.innerHTML=`<button class="back" id="back">← Danh sách HSKK</button><section class="learning-shell"><div id="hskkDetail" class="loading-box">Đang mở bài luyện…</div></section>`;document.querySelector('#back').onclick=()=>history.back();try{const j=await getJson('/hsk/hskk-set?id='+encodeURIComponent(state.hskkId)),set=j.set||{},prompts=j.prompts||[],box=document.querySelector('#hskkDetail');box.innerHTML=titleBlock('LUYỆN NÓI HSKK',esc(set.title),`<span class="waiting">${Number(set.duration_minutes)||0} phút</span>`)+`<p class="intro">${esc(set.instructions||'Nghe hoặc đọc đề, chuẩn bị rồi luyện nói.')}</p><div class="exam-questions">${prompts.map((p,i)=>`<article class="exam-question"><small>Câu ${i+1} · Chuẩn bị ${Number(p.preparation_seconds)||0}s · Trả lời ${Number(p.response_seconds)||0}s</small><h3>${esc(p.prompt_hanzi||p.prompt_vi)}</h3>${p.prompt_pinyin?`<p class="pinyin">${esc(p.prompt_pinyin)}</p>`:''}${p.prompt_vi?`<p>${esc(p.prompt_vi)}</p>`:''}${p.audio_url?`<audio controls preload="none" src="${esc(p.audio_url)}"></audio>`:''}${p.image_url?`<img src="${esc(p.image_url)}" alt="Hình luyện nói ${i+1}">`:''}<textarea rows="3" placeholder="Ghi chú câu trả lời"></textarea></article>`).join('')}</div><button class="primary" id="finishHskk">Hoàn thành bài luyện</button><div class="status-line" id="hskkResult"></div>`;document.querySelector('#finishHskk').onclick=()=>{localStorage.setItem('aluni_hsk_hskk_'+state.hskkId,JSON.stringify({type:'hskk',title:set.title||'Bài luyện HSKK',updated_at:Date.now()}));document.querySelector('#hskkResult').textContent='Đã lưu kết quả luyện trên thiết bị này.'}}catch(e){document.querySelector('#hskkDetail').innerHTML=emptyModule('↻','Chưa mở được bài HSKK',esc(e.message))}}
function savedProgress(){const rows=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key?.startsWith('aluni_hsk_'))continue;try{const raw=localStorage.getItem(key),parsed=JSON.parse(raw),legacyTime=typeof parsed==='number'?parsed:0,item=typeof parsed==='object'&&parsed?parsed:{};let type=item.type||(key.startsWith('aluni_hsk_exam_')?'exam':key.startsWith('aluni_hsk_hskk_')?'hskk':'grammar');rows.push({...item,key,type,title:item.title||(type==='exam'?'Đề luyện HSK':type==='hskk'?'Bài luyện HSKK':'Ngữ pháp & Bài tập'),updated_at:Number(item.updated_at||legacyTime)||0})}catch{const stamp=Number(localStorage.getItem(key));if(stamp)rows.push({key,type:'hskk',title:'Bài luyện HSKK',updated_at:stamp})}}return rows.sort((a,b)=>b.updated_at-a.updated_at)}
function progressLabel(item){if(item.type==='hskk')return 'Đã hoàn thành';const got=Number(item.score??item.correct??0),total=Number(item.total||0);return total?`${got}/${total} · ${Math.round(got/total*100)}%`:'Đã lưu'}
function renderProgress(){const rows=savedProgress(),scored=rows.filter(x=>x.type!=='hskk'&&Number(x.total)>0),average=scored.length?Math.round(scored.reduce((sum,x)=>sum+(Number(x.score??x.correct??0)/Number(x.total)*100),0)/scored.length):0,days=new Set(rows.filter(x=>x.updated_at).map(x=>new Date(x.updated_at).toLocaleDateString('vi-VN'))).size,recent=rows.slice(0,8);app.innerHTML=titleBlock("Kết quả học tập","Hành trình của bạn")+`<section class="progress"><div class="card progress-card"><div class="metrics"><div class="metric"><b>${rows.length}</b><small>Bài hoàn thành</small></div><div class="metric"><b>${average}%</b><small>Điểm trung bình</small></div><div class="metric"><b>${days}</b><small>Ngày học</small></div></div><div class="progress-history"><h3>Lịch sử gần đây</h3>${recent.length?recent.map(x=>`<article><span><b>${esc(x.title)}</b><small>${x.updated_at?new Date(x.updated_at).toLocaleString('vi-VN'):'Đã lưu trên thiết bị'}</small></span><strong>${esc(progressLabel(x))}</strong></article>`).join(''):'<div class="empty-list">Chưa có kết quả. Hãy làm một đề HSK hoặc hoàn thành bài HSKK đầu tiên nhé!</div>'}</div><p class="progress-note">Kết quả đang được lưu riêng trên trình duyệt này. Không cần đăng nhập để học và xem lại.</p></div><aside class="panel-side progress-login"><h3>Đăng nhập khi bạn muốn</h3><p>Sau này tài khoản sẽ giúp đồng bộ tiến độ giữa điện thoại và máy tính. Hiện tại việc đăng nhập hoàn toàn không bắt buộc.</p><a class="primary" href="https://tieng-trung-aluni.nhangohcm.chatgpt.site/" target="_blank" rel="noopener">Tìm hiểu khóa học</a></aside></section>`}
render();
