const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:JSON_HEADERS});
const id=(prefix)=>`${prefix}_${crypto.randomUUID()}`;
const clean=v=>String(v??'').trim();
const number=(v,fallback=0)=>Number.isFinite(Number(v))?Number(v):fallback;

async function body(request){try{return await request.json()}catch{return null}}
function requireAdmin(auth){if(!auth?.isAdmin)throw Object.assign(new Error('Admin authorization required.'),{status:403})}
function statusValue(v){return['draft','published','hidden'].includes(v)?v:'draft'}
function examVersion(v){if(!['hsk20','hsk30'].includes(v))throw Object.assign(new Error('Invalid HSK version.'),{status:400});return v}
function hskkLevel(v){if(!['primary','intermediate','advanced'].includes(v))throw Object.assign(new Error('Invalid HSKK level.'),{status:400});return v}

async function listExamSets(env,admin=false){const where=admin?'deleted_at IS NULL':"status='published' AND deleted_at IS NULL";const rows=await env.DB.prepare(`SELECT id,version,level,code,title,duration_minutes,instructions,status,created_at,updated_at FROM hsk_exam_sets WHERE ${where} ORDER BY version,level,code`).all();return json({sets:rows.results||[]})}
async function getExam(env,examId,admin=false){const visibility=admin?'':' AND status=\'published\'';const set=await env.DB.prepare(`SELECT * FROM hsk_exam_sets WHERE id=? AND deleted_at IS NULL${visibility}`).bind(examId).first();if(!set)return json({error:'Exam not found.'},404);const questions=await env.DB.prepare('SELECT * FROM hsk_exam_questions WHERE exam_id=? ORDER BY question_no').bind(examId).all();if(!admin)(questions.results||[]).forEach(q=>delete q.correct_answer);return json({set,questions:questions.results||[]})}

function validateExam(payload){const set=payload?.set||{},questions=Array.isArray(payload?.questions)?payload.questions:[];examVersion(set.version);const level=number(set.level);if(level<1||level>6)throw Object.assign(new Error('Invalid HSK level.'),{status:400});if(!clean(set.code)||!clean(set.title))throw Object.assign(new Error('Exam code and title are required.'),{status:400});if(!questions.length)throw Object.assign(new Error('At least one question is required.'),{status:400});const seen=new Set();questions.forEach(q=>{const n=number(q.question_no);if(n<1||seen.has(n))throw Object.assign(new Error(`Invalid or duplicate question number: ${q.question_no}`),{status:400});seen.add(n)});return{set:{...set,level},questions}}
async function importExam(request,env,auth){requireAdmin(auth);const payload=validateExam(await body(request)),examId=clean(payload.set.id)||id('exam'),now=new Date().toISOString();const statements=[env.DB.prepare(`INSERT INTO hsk_exam_sets(id,version,level,code,title,duration_minutes,instructions,status,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(code) DO UPDATE SET version=excluded.version,level=excluded.level,title=excluded.title,duration_minutes=excluded.duration_minutes,instructions=excluded.instructions,status=excluded.status,updated_at=excluded.updated_at,deleted_at=NULL`).bind(examId,payload.set.version,payload.set.level,clean(payload.set.code),clean(payload.set.title),number(payload.set.duration_minutes),clean(payload.set.instructions),statusValue(payload.set.status),now)];for(const q of payload.questions)statements.push(env.DB.prepare(`INSERT INTO hsk_exam_questions(id,exam_id,section,question_no,question_type,prompt,passage,audio_url,image_url,options_json,correct_answer,explanation,points,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(exam_id,question_no) DO UPDATE SET section=excluded.section,question_type=excluded.question_type,prompt=excluded.prompt,passage=excluded.passage,audio_url=excluded.audio_url,image_url=excluded.image_url,options_json=excluded.options_json,correct_answer=excluded.correct_answer,explanation=excluded.explanation,points=excluded.points,updated_at=excluded.updated_at`).bind(clean(q.id)||id('eq'),examId,clean(q.section),number(q.question_no),clean(q.question_type),clean(q.prompt),clean(q.passage),clean(q.audio_url),clean(q.image_url),JSON.stringify(q.options||[]),clean(q.correct_answer),clean(q.explanation),number(q.points,1),now));statements.push(env.DB.prepare('INSERT INTO hsk_import_audit(id,content_type,source_filename,record_id,action,actor,details_json) VALUES(?,?,?,?,?,?,?)').bind(id('audit'),'exam',clean(payload.source_filename),examId,payload.set.id?'update':'create',clean(auth.actor),JSON.stringify({questions:payload.questions.length})));await env.DB.batch(statements);return json({ok:true,id:examId,questions:payload.questions.length},201)}

async function listHskkSets(env,admin=false){const where=admin?'deleted_at IS NULL':"status='published' AND deleted_at IS NULL";const rows=await env.DB.prepare(`SELECT id,level,code,title,duration_minutes,instructions,status,created_at,updated_at FROM hskk_sets WHERE ${where} ORDER BY level,code`).all();return json({sets:rows.results||[]})}
async function getHskk(env,setId,admin=false){const visibility=admin?'':' AND status=\'published\'';const set=await env.DB.prepare(`SELECT * FROM hskk_sets WHERE id=? AND deleted_at IS NULL${visibility}`).bind(setId).first();if(!set)return json({error:'HSKK set not found.'},404);const [prompts,criteria]=await Promise.all([env.DB.prepare('SELECT * FROM hskk_prompts WHERE set_id=? ORDER BY item_no').bind(setId).all(),env.DB.prepare('SELECT * FROM hskk_criteria WHERE set_id=? ORDER BY sort_order,criterion_code').bind(setId).all()]);return json({set,prompts:prompts.results||[],criteria:criteria.results||[]})}

function validateHskk(payload){const set=payload?.set||{},prompts=Array.isArray(payload?.prompts)?payload.prompts:[],criteria=Array.isArray(payload?.criteria)?payload.criteria:[];hskkLevel(set.level);if(!clean(set.code)||!clean(set.title))throw Object.assign(new Error('HSKK code and title are required.'),{status:400});if(!prompts.length)throw Object.assign(new Error('At least one HSKK prompt is required.'),{status:400});return{set,prompts,criteria}}
async function importHskk(request,env,auth){requireAdmin(auth);const payload=validateHskk(await body(request)),setId=clean(payload.set.id)||id('hskk'),now=new Date().toISOString();const statements=[env.DB.prepare(`INSERT INTO hskk_sets(id,level,code,title,duration_minutes,instructions,status,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(code) DO UPDATE SET level=excluded.level,title=excluded.title,duration_minutes=excluded.duration_minutes,instructions=excluded.instructions,status=excluded.status,updated_at=excluded.updated_at,deleted_at=NULL`).bind(setId,payload.set.level,clean(payload.set.code),clean(payload.set.title),number(payload.set.duration_minutes),clean(payload.set.instructions),statusValue(payload.set.status),now)];for(const p of payload.prompts)statements.push(env.DB.prepare(`INSERT INTO hskk_prompts(id,set_id,item_no,task_type,prompt_hanzi,prompt_pinyin,prompt_vi,audio_url,image_url,preparation_seconds,response_seconds,sample_answer,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(set_id,item_no) DO UPDATE SET task_type=excluded.task_type,prompt_hanzi=excluded.prompt_hanzi,prompt_pinyin=excluded.prompt_pinyin,prompt_vi=excluded.prompt_vi,audio_url=excluded.audio_url,image_url=excluded.image_url,preparation_seconds=excluded.preparation_seconds,response_seconds=excluded.response_seconds,sample_answer=excluded.sample_answer,updated_at=excluded.updated_at`).bind(clean(p.id)||id('hp'),setId,number(p.item_no),clean(p.task_type),clean(p.prompt_hanzi),clean(p.prompt_pinyin),clean(p.prompt_vi),clean(p.audio_url),clean(p.image_url),number(p.preparation_seconds),number(p.response_seconds),clean(p.sample_answer),now));for(const c of payload.criteria)statements.push(env.DB.prepare(`INSERT INTO hskk_criteria(id,set_id,criterion_code,title,description,max_score,sort_order) VALUES(?,?,?,?,?,?,?) ON CONFLICT(set_id,criterion_code) DO UPDATE SET title=excluded.title,description=excluded.description,max_score=excluded.max_score,sort_order=excluded.sort_order`).bind(clean(c.id)||id('hc'),setId,clean(c.criterion_code),clean(c.title),clean(c.description),number(c.max_score),number(c.sort_order)));statements.push(env.DB.prepare('INSERT INTO hsk_import_audit(id,content_type,source_filename,record_id,action,actor,details_json) VALUES(?,?,?,?,?,?,?)').bind(id('audit'),'hskk',clean(payload.source_filename),setId,payload.set.id?'update':'create',clean(auth.actor),JSON.stringify({prompts:payload.prompts.length,criteria:payload.criteria.length})));await env.DB.batch(statements);return json({ok:true,id:setId,prompts:payload.prompts.length,criteria:payload.criteria.length},201)}

async function changeSet(request,env,auth,type,setId){requireAdmin(auth);const data=await body(request)||{},table=type==='exam'?'hsk_exam_sets':'hskk_sets',contentType=type==='exam'?'exam':'hskk';if(request.method==='DELETE'){await env.DB.batch([env.DB.prepare(`UPDATE ${table} SET deleted_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(setId),env.DB.prepare('INSERT INTO hsk_import_audit(id,content_type,record_id,action,actor) VALUES(?,?,?,?,?)').bind(id('audit'),contentType,setId,'delete',clean(auth.actor))]);return json({ok:true,deleted:true})}const next=statusValue(data.status);await env.DB.batch([env.DB.prepare(`UPDATE ${table} SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND deleted_at IS NULL`).bind(next,setId),env.DB.prepare('INSERT INTO hsk_import_audit(id,content_type,record_id,action,actor) VALUES(?,?,?,?,?)').bind(id('audit'),contentType,setId,next==='published'?'publish':'hide',clean(auth.actor))]);return json({ok:true,status:next})}

// Integrate this before the existing Worker's 404 response.
// auth must be supplied by the existing Aluni admin authentication layer.
export async function handleHskRequest(request,env,auth={isAdmin:false,actor:''}){
  const url=new URL(request.url),p=url.pathname;
  try{
    if(request.method==='GET'&&p==='/hsk/exams')return listExamSets(env,false);
    if(request.method==='GET'&&p.startsWith('/hsk/exams/'))return getExam(env,decodeURIComponent(p.slice(11)),false);
    if(request.method==='GET'&&p==='/hsk/hskk')return listHskkSets(env,false);
    if(request.method==='GET'&&p.startsWith('/hsk/hskk/'))return getHskk(env,decodeURIComponent(p.slice(10)),false);
    if(request.method==='GET'&&p==='/hsk-admin/exams'){requireAdmin(auth);return listExamSets(env,true)}
    if(request.method==='POST'&&p==='/hsk-admin/exams/import')return importExam(request,env,auth);
    if(['PATCH','DELETE'].includes(request.method)&&p.startsWith('/hsk-admin/exams/'))return changeSet(request,env,auth,'exam',decodeURIComponent(p.slice(18)));
    if(request.method==='GET'&&p==='/hsk-admin/hskk'){requireAdmin(auth);return listHskkSets(env,true)}
    if(request.method==='POST'&&p==='/hsk-admin/hskk/import')return importHskk(request,env,auth);
    if(['PATCH','DELETE'].includes(request.method)&&p.startsWith('/hsk-admin/hskk/'))return changeSet(request,env,auth,'hskk',decodeURIComponent(p.slice(17)));
    return null;
  }catch(error){return json({error:error.message||'HSK API error.'},error.status||500)}
}
